# Generated by Django 5.0.7 on 2025-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Имя')),
                ('lname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('about', models.TextField(max_length=300, verbose_name='О себе')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
