# Generated by Django 5.0.7 on 2025-12-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='email',
        ),
        migrations.AddField(
            model_name='datauser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
