# Generated by Django 5.0.7 on 2025-12-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogactivity',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='blogactivity',
            name='like',
        ),
        migrations.AddField(
            model_name='blogactivity',
            name='action',
            field=models.CharField(blank=True, choices=[('like', 'Лайк'), ('hide', 'Скрытие'), ('comment', 'Комментарий')], max_length=10, null=True),
        ),
    ]
